### ISSUE TITLE
Issue when run zx start

### ISSUE THREAD

**Issue by montanojd** [zuixjs/news-blog#1]
Hello, i like this code it is really cool, i am trying to install it but i got this issue 

C:\Users\PERSONAL\AppData\Roaming\npm\node_modules\zuix-cli\node_modules\string-kit\lib\format.js:327
                markupTarget = this.shiftedMarkup?.[ runtime.shift ]?.[ markup ] ;
                                                  ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1047:16)
    at Module._compile (internal/modules/cjs/loader.js:1097:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\PERSONAL\AppData\Roaming\npm\node_modules\zuix-cli\node_modules\string-kit\lib\string.js:62:2)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)

**Comment by genemars** [comment]
Should be fixed now. The `zx` command has been renamed to `zuix`:
```shell
npx zuix start
```
See [updated docs](https://github.com/zuixjs/news-blog#getting-started).
Let me know if it works for you also. If not, please provide further details, such as the OS and node version.

**Comment by genemars** [comment]
@montanojd the issue seems similar to [this one](https://github.com/foundation/foundation-sites/discussions/12309#discussioncomment-1579207).

**Comment by montanojd** [comment]
> Should be fixed now. The `zx` command has been renamed to `zuix`:
> 
> ```shell
> npx zuix start
> ```
> 
> See [updated docs](https://github.com/zuixjs/news-blog#getting-started). Let me know if it works for you also. If not, please provide further details, such as the OS and node version.

Great Thanks, i will try justt now

**Comment by montanojd** [comment]
> Should be fixed now. The `zx` command has been renamed to `zuix`:
> 
> ```shell
> npx zuix start
> ```
> 
> See [updated docs](https://github.com/zuixjs/news-blog#getting-started). Let me know if it works for you also. If not, please provide further details, such as the OS and node version.

Hello, still the same - Os Windows10
![image](https://user-images.githubusercontent.com/60124037/158884485-652affb8-9c16-4463-9dc9-479932c1fcb6.png)

**Comment by genemars** [comment]
Can you try upgrading node >= 14?

**Comment by montanojd** [comment]
> Can you try upgrading node >= 14?
i got this in node 14.19.0
![image](https://user-images.githubusercontent.com/60124037/158899434-02d11096-8167-4b6e-8774-1012f61c354c.png)

**Comment by genemars** [comment]
I better add some CI tests soon =) Sorry about that, quote from StackOverflow:

> Nodejs v14 has V8 8.4 But, replaceAll was added to V8 8.5. Nodejs v15 has V8 8.6 and thus that's the first nodejs version where you can use .replaceAll().

I should update the required node version to >= 15 in the docs I guess, or I can try to replace `replaceAll` with something else.
I added that code this morning, but I only tested on node V17.

**Comment by genemars** [comment]
@montanojd I just updated *zuix* CLI so that it's not using `replaceAll'. I also updated this repository.
I cannot test with node v14 right now, so let me know if it works.

**Comment by montanojd** [comment]
> @montanojd I just updated _zuix_ CLI so that it's not using `replaceAll'. I also updated this repository. I cannot test with node v14 right now, so let me know if it works.

It Works!! thanks.. to add text to the blog is it done from terminal?
![image](https://user-images.githubusercontent.com/60124037/158910622-1eaea8fc-3bb7-4223-be2e-6f3f46aa241e.png)

**Comment by genemars** [comment]
You can add new pages either manually or from a new terminal. It's all explained in the [documentation](https://github.com/zuixjs/news-blog#commands).
I have already plans to make it possible to manage content directly from the browser.
In the actual version the pop-up menu in the main section pages is not enabled yet but it will be fully working in the next days.
To upgrade to a new version you can either use `git pull` (if you cloned this repo using `git`) or just download the new version and replace the `./pages` folder with your data.
Since this is a work-in-progress, feel free to ask for support or any feature request.

**Comment by genemars** [comment]
@montanojd, just to let you know I finished implementing the missing functionalities (the pop-up menu options and bookmarks page) and updated the repo.

**Comment by montanojd** [comment]
> @montanojd, just to let you know I finished implementing the missing functionalities (the pop-up menu options and bookmarks page) and updated the repo.

Great Keep the Work, it would be nice to have Dark mode, i will try the code just now. Thanks

**Comment by genemars** [comment]
Definitely dark-mode would be nice. Please close this issue and open a new one for the dark-mode feature request.
